#!/usr/bin/env bash
set -euo pipefail

# Regenerates charts/env/prod/argocd-apps.yaml from the chart directories
# under charts/env/prod/{central-services,critical,apps} so the Argo CD
# Application set stays in sync with what charts actually exist, instead
# of being hand-maintained.
#
# Per-chart extra Helm parameters (e.g. greeter's image.repository/tag)
# are picked up from an optional <chart-dir>/argocd-params.env file --
# simple KEY=VALUE lines, one per Helm parameter path.
#
# Namespace defaults per category (below), but a chart whose install
# namespace doesn't match its category's default (e.g. cert-manager,
# which needs its own namespace to match its IRSA trust policy rather
# than critical/'s kube-system default) can override it with a one-line
# <chart-dir>/argocd-namespace file.
#
# Usage: scripts/generate-argocd-apps.sh
# Env overrides: REPO_URL, TARGET_REVISION, OUTPUT_FILE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHARTS_ROOT="${REPO_ROOT}/charts/env/prod"

REPO_URL="${REPO_URL:-git@github.com:chayma1205/hivemind-challenge.git}"
TARGET_REVISION="${TARGET_REVISION:-main}"
OUTPUT_FILE="${OUTPUT_FILE:-${CHARTS_ROOT}/argocd-apps.yaml}"

# category -> destination namespace (apps/* namespaces itself per chart name)
declare -A CATEGORY_NAMESPACE=(
  [central-services]="argocd"
  [critical]="kube-system"
)

emit_root_app() {
  # Argo CD Application for this file itself, so that once it's applied
  # (the one manual bootstrap step), every future regeneration of this
  # file — including the CD pipeline's own commits bumping
  # greeter's image tag — gets picked up and applied automatically.
  # Without this, argocd-apps.yaml is just a plain manifest nobody
  # watches: `kubectl apply` once, then silently stale forever after.
  cat <<EOF
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${TARGET_REVISION}
    path: charts/env/prod
    directory:
      include: "argocd-apps.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
EOF
}

emit_app() {
  local name="$1" path="$2" namespace="$3" params_file="$4"

  cat <<EOF
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${TARGET_REVISION}
    path: ${path}
    helm:
      valueFiles:
        - values.yaml
EOF

  if [[ -f "${params_file}" ]]; then
    echo "      parameters:"
    while IFS='=' read -r key value; do
      [[ -z "${key}" || "${key}" == \#* ]] && continue
      echo "        - name: ${key}"
      echo "          value: \"${value}\""
    done < "${params_file}"
  fi

  cat <<EOF
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Confirmed live, needed for kube-prometheus-stack specifically:
      # the Prometheus Operator's CRDs (Prometheus, Alertmanager, ...)
      # are large enough that kubectl's client-side apply
      # (last-applied-configuration annotation) exceeds Kubernetes's
      # 256KiB annotation size limit, failing every sync attempt with
      # "metadata.annotations: Too long" and silently blocking the rest
      # of that sync operation's changes too (this is how an unrelated
      # Grafana values.yaml fix never reached the cluster despite
      # several syncs "succeeding"). Server-Side Apply doesn't use that
      # annotation at all, so it doesn't hit the limit. Applied to every
      # Application, not just that one, since it's the same well-known
      # fix and there's no real downside for charts too small to hit
      # this problem — one behavior for all Applications, not a
      # special case.
      - ServerSideApply=true
EOF
}

{
  cat <<HEADER
# Argo CD Application set for the hivemind-prod cluster ("app of apps").
#
# GENERATED by scripts/generate-argocd-apps.sh -- do not hand-edit.
# Re-run the script after adding/removing a chart under charts/env/prod/,
# or after changing a chart's argocd-params.env.
#
# Apply once Argo CD itself is running (see
# charts/env/prod/central-services/argocd/README.md for the bootstrap
# \`helm install\`):
#
#   kubectl apply -n argocd -f charts/env/prod/argocd-apps.yaml
#
# This repo is private (see docs/DECISIONS.md #10), so Argo CD clones it
# over SSH using a registered deploy-key credential — see
# charts/env/prod/central-services/argocd/README.md.
#
# The "root" Application below watches this exact file, so re-applying it
# by hand is a one-time bootstrap step -- every regeneration after that
# (e.g. the CD pipeline bumping greeter's image tag) is picked up and
# applied automatically, no further kubectl needed.
#
# Each Application below is independent -- a missing prerequisite in one
# chart (see that chart's README) only leaves that Application
# OutOfSync/Degraded, it doesn't block the others.
HEADER

  emit_root_app

  for category in central-services critical; do
    dir="${CHARTS_ROOT}/${category}"
    [[ -d "${dir}" ]] || continue
    for chart_dir in "${dir}"/*/; do
      [[ -f "${chart_dir}/Chart.yaml" ]] || continue
      name="$(basename "${chart_dir}")"
      namespace="${CATEGORY_NAMESPACE[${category}]}"
      [[ -f "${chart_dir}argocd-namespace" ]] && namespace="$(<"${chart_dir}argocd-namespace")"
      emit_app "${name}" "charts/env/prod/${category}/${name}" \
        "${namespace}" "${chart_dir}argocd-params.env"
    done
  done

  apps_dir="${CHARTS_ROOT}/apps"
  if [[ -d "${apps_dir}" ]]; then
    for chart_dir in "${apps_dir}"/*/; do
      [[ -f "${chart_dir}/Chart.yaml" ]] || continue
      name="$(basename "${chart_dir}")"
      emit_app "${name}" "charts/env/prod/apps/${name}" "${name}" "${chart_dir}argocd-params.env"
    done
  fi
} > "${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE}" >&2
