#!/usr/bin/env bash
set -euo pipefail

# Regenerates charts/env/prod/argocd-apps.yaml from the chart directories
# under charts/env/prod/{central-services,critical,apps} so the Argo CD
# Application set stays in sync with what charts actually exist, instead
# of being hand-maintained.
#
# Per-chart extra Helm parameters (e.g. greeter's image.repository/tag)
# are picked up from an optional <chart-dir>/argocd-params.env file --
# simple KEY=VALUE lines, one per Helm parameter path.
#
# Usage: scripts/generate-argocd-apps.sh
# Env overrides: REPO_URL, TARGET_REVISION, OUTPUT_FILE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHARTS_ROOT="${REPO_ROOT}/charts/env/prod"

REPO_URL="${REPO_URL:-https://github.com/chayma1205/hivemind-challenge.git}"
TARGET_REVISION="${TARGET_REVISION:-main}"
OUTPUT_FILE="${OUTPUT_FILE:-${CHARTS_ROOT}/argocd-apps.yaml}"

# category -> destination namespace (apps/* namespaces itself per chart name)
declare -A CATEGORY_NAMESPACE=(
  [central-services]="argocd"
  [critical]="kube-system"
)

emit_app() {
  local name="$1" path="$2" namespace="$3" params_file="$4"

  cat <<EOF
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${TARGET_REVISION}
    path: ${path}
    helm:
      valueFiles:
        - values.yaml
EOF

  if [[ -f "${params_file}" ]]; then
    echo "      parameters:"
    while IFS='=' read -r key value; do
      [[ -z "${key}" || "${key}" == \#* ]] && continue
      echo "        - name: ${key}"
      echo "          value: \"${value}\""
    done < "${params_file}"
  fi

  cat <<EOF
  destination:
    server: https://kubernetes.default.svc
    namespace: ${namespace}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF
}

{
  cat <<HEADER
# Argo CD Application set for the hivemind-prod cluster ("app of apps").
#
# GENERATED by scripts/generate-argocd-apps.sh -- do not hand-edit.
# Re-run the script after adding/removing a chart under charts/env/prod/,
# or after changing a chart's argocd-params.env.
#
# Apply once Argo CD itself is running (see
# charts/env/prod/central-services/argocd/README.md for the bootstrap
# \`helm install\`):
#
#   kubectl apply -n argocd -f charts/env/prod/argocd-apps.yaml
#
# Prerequisite: Argo CD needs read access to this repo (it's private).
# Register it once, e.g.:
#
#   argocd repo add ${REPO_URL} \\
#     --username <gh-user> --password <gh-PAT-with-repo-scope>
#
# Each Application below is independent -- a missing prerequisite in one
# chart (see that chart's README) only leaves that Application
# OutOfSync/Degraded, it doesn't block the others.
HEADER

  for category in central-services critical; do
    dir="${CHARTS_ROOT}/${category}"
    [[ -d "${dir}" ]] || continue
    for chart_dir in "${dir}"/*/; do
      [[ -f "${chart_dir}/Chart.yaml" ]] || continue
      name="$(basename "${chart_dir}")"
      emit_app "${name}" "charts/env/prod/${category}/${name}" \
        "${CATEGORY_NAMESPACE[${category}]}" "${chart_dir}argocd-params.env"
    done
  done

  apps_dir="${CHARTS_ROOT}/apps"
  if [[ -d "${apps_dir}" ]]; then
    for chart_dir in "${apps_dir}"/*/; do
      [[ -f "${chart_dir}/Chart.yaml" ]] || continue
      name="$(basename "${chart_dir}")"
      emit_app "${name}" "charts/env/prod/apps/${name}" "${name}" "${chart_dir}argocd-params.env"
    done
  fi
} > "${OUTPUT_FILE}"

echo "Wrote ${OUTPUT_FILE}" >&2
